/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddFaxEmailNotificationRequest struct for AddFaxEmailNotificationRequest
type AddFaxEmailNotificationRequest struct {
	FaxlineId string `json:"faxlineId"`
	Direction string `json:"direction"`
	Email string `json:"email"`
}

// NewAddFaxEmailNotificationRequest instantiates a new AddFaxEmailNotificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddFaxEmailNotificationRequest(faxlineId string, direction string, email string) *AddFaxEmailNotificationRequest {
	this := AddFaxEmailNotificationRequest{}
	this.FaxlineId = faxlineId
	this.Direction = direction
	this.Email = email
	return &this
}

// NewAddFaxEmailNotificationRequestWithDefaults instantiates a new AddFaxEmailNotificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddFaxEmailNotificationRequestWithDefaults() *AddFaxEmailNotificationRequest {
	this := AddFaxEmailNotificationRequest{}
	return &this
}

// GetFaxlineId returns the FaxlineId field value
func (o *AddFaxEmailNotificationRequest) GetFaxlineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FaxlineId
}

// GetFaxlineIdOk returns a tuple with the FaxlineId field value
// and a boolean to check if the value has been set.
func (o *AddFaxEmailNotificationRequest) GetFaxlineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FaxlineId, true
}

// SetFaxlineId sets field value
func (o *AddFaxEmailNotificationRequest) SetFaxlineId(v string) {
	o.FaxlineId = v
}

// GetDirection returns the Direction field value
func (o *AddFaxEmailNotificationRequest) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *AddFaxEmailNotificationRequest) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *AddFaxEmailNotificationRequest) SetDirection(v string) {
	o.Direction = v
}

// GetEmail returns the Email field value
func (o *AddFaxEmailNotificationRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AddFaxEmailNotificationRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AddFaxEmailNotificationRequest) SetEmail(v string) {
	o.Email = v
}

func (o AddFaxEmailNotificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["faxlineId"] = o.FaxlineId
	}
	if true {
		toSerialize["direction"] = o.Direction
	}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableAddFaxEmailNotificationRequest struct {
	value *AddFaxEmailNotificationRequest
	isSet bool
}

func (v NullableAddFaxEmailNotificationRequest) Get() *AddFaxEmailNotificationRequest {
	return v.value
}

func (v *NullableAddFaxEmailNotificationRequest) Set(val *AddFaxEmailNotificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddFaxEmailNotificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddFaxEmailNotificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddFaxEmailNotificationRequest(val *AddFaxEmailNotificationRequest) *NullableAddFaxEmailNotificationRequest {
	return &NullableAddFaxEmailNotificationRequest{value: val, isSet: true}
}

func (v NullableAddFaxEmailNotificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddFaxEmailNotificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


