/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VerifySmsCallerIdRequest struct for VerifySmsCallerIdRequest
type VerifySmsCallerIdRequest struct {
	VerificationCode *string `json:"verificationCode,omitempty"`
}

// NewVerifySmsCallerIdRequest instantiates a new VerifySmsCallerIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifySmsCallerIdRequest() *VerifySmsCallerIdRequest {
	this := VerifySmsCallerIdRequest{}
	return &this
}

// NewVerifySmsCallerIdRequestWithDefaults instantiates a new VerifySmsCallerIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifySmsCallerIdRequestWithDefaults() *VerifySmsCallerIdRequest {
	this := VerifySmsCallerIdRequest{}
	return &this
}

// GetVerificationCode returns the VerificationCode field value if set, zero value otherwise.
func (o *VerifySmsCallerIdRequest) GetVerificationCode() string {
	if o == nil || o.VerificationCode == nil {
		var ret string
		return ret
	}
	return *o.VerificationCode
}

// GetVerificationCodeOk returns a tuple with the VerificationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySmsCallerIdRequest) GetVerificationCodeOk() (*string, bool) {
	if o == nil || o.VerificationCode == nil {
		return nil, false
	}
	return o.VerificationCode, true
}

// HasVerificationCode returns a boolean if a field has been set.
func (o *VerifySmsCallerIdRequest) HasVerificationCode() bool {
	if o != nil && o.VerificationCode != nil {
		return true
	}

	return false
}

// SetVerificationCode gets a reference to the given string and assigns it to the VerificationCode field.
func (o *VerifySmsCallerIdRequest) SetVerificationCode(v string) {
	o.VerificationCode = &v
}

func (o VerifySmsCallerIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VerificationCode != nil {
		toSerialize["verificationCode"] = o.VerificationCode
	}
	return json.Marshal(toSerialize)
}

type NullableVerifySmsCallerIdRequest struct {
	value *VerifySmsCallerIdRequest
	isSet bool
}

func (v NullableVerifySmsCallerIdRequest) Get() *VerifySmsCallerIdRequest {
	return v.value
}

func (v *NullableVerifySmsCallerIdRequest) Set(val *VerifySmsCallerIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifySmsCallerIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifySmsCallerIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifySmsCallerIdRequest(val *VerifySmsCallerIdRequest) *NullableVerifySmsCallerIdRequest {
	return &NullableVerifySmsCallerIdRequest{value: val, isSet: true}
}

func (v NullableVerifySmsCallerIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifySmsCallerIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


