/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InternalContactsResponse struct for InternalContactsResponse
type InternalContactsResponse struct {
	Items []InternalContactResponse `json:"items,omitempty"`
}

// NewInternalContactsResponse instantiates a new InternalContactsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalContactsResponse() *InternalContactsResponse {
	this := InternalContactsResponse{}
	return &this
}

// NewInternalContactsResponseWithDefaults instantiates a new InternalContactsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalContactsResponseWithDefaults() *InternalContactsResponse {
	this := InternalContactsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *InternalContactsResponse) GetItems() []InternalContactResponse {
	if o == nil || o.Items == nil {
		var ret []InternalContactResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalContactsResponse) GetItemsOk() ([]InternalContactResponse, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *InternalContactsResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []InternalContactResponse and assigns it to the Items field.
func (o *InternalContactsResponse) SetItems(v []InternalContactResponse) {
	o.Items = v
}

func (o InternalContactsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableInternalContactsResponse struct {
	value *InternalContactsResponse
	isSet bool
}

func (v NullableInternalContactsResponse) Get() *InternalContactsResponse {
	return v.value
}

func (v *NullableInternalContactsResponse) Set(val *InternalContactsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalContactsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalContactsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalContactsResponse(val *InternalContactsResponse) *NullableInternalContactsResponse {
	return &NullableInternalContactsResponse{value: val, isSet: true}
}

func (v NullableInternalContactsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalContactsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


