/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmsExtensionResponse struct for SmsExtensionResponse
type SmsExtensionResponse struct {
	Id *string `json:"id,omitempty"`
	Alias *string `json:"alias,omitempty"`
	CallerId *string `json:"callerId,omitempty"`
}

// NewSmsExtensionResponse instantiates a new SmsExtensionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsExtensionResponse() *SmsExtensionResponse {
	this := SmsExtensionResponse{}
	return &this
}

// NewSmsExtensionResponseWithDefaults instantiates a new SmsExtensionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsExtensionResponseWithDefaults() *SmsExtensionResponse {
	this := SmsExtensionResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SmsExtensionResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsExtensionResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SmsExtensionResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SmsExtensionResponse) SetId(v string) {
	o.Id = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *SmsExtensionResponse) GetAlias() string {
	if o == nil || o.Alias == nil {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsExtensionResponse) GetAliasOk() (*string, bool) {
	if o == nil || o.Alias == nil {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *SmsExtensionResponse) HasAlias() bool {
	if o != nil && o.Alias != nil {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *SmsExtensionResponse) SetAlias(v string) {
	o.Alias = &v
}

// GetCallerId returns the CallerId field value if set, zero value otherwise.
func (o *SmsExtensionResponse) GetCallerId() string {
	if o == nil || o.CallerId == nil {
		var ret string
		return ret
	}
	return *o.CallerId
}

// GetCallerIdOk returns a tuple with the CallerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsExtensionResponse) GetCallerIdOk() (*string, bool) {
	if o == nil || o.CallerId == nil {
		return nil, false
	}
	return o.CallerId, true
}

// HasCallerId returns a boolean if a field has been set.
func (o *SmsExtensionResponse) HasCallerId() bool {
	if o != nil && o.CallerId != nil {
		return true
	}

	return false
}

// SetCallerId gets a reference to the given string and assigns it to the CallerId field.
func (o *SmsExtensionResponse) SetCallerId(v string) {
	o.CallerId = &v
}

func (o SmsExtensionResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Alias != nil {
		toSerialize["alias"] = o.Alias
	}
	if o.CallerId != nil {
		toSerialize["callerId"] = o.CallerId
	}
	return json.Marshal(toSerialize)
}

type NullableSmsExtensionResponse struct {
	value *SmsExtensionResponse
	isSet bool
}

func (v NullableSmsExtensionResponse) Get() *SmsExtensionResponse {
	return v.value
}

func (v *NullableSmsExtensionResponse) Set(val *SmsExtensionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsExtensionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsExtensionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsExtensionResponse(val *SmsExtensionResponse) *NullableSmsExtensionResponse {
	return &NullableSmsExtensionResponse{value: val, isSet: true}
}

func (v NullableSmsExtensionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsExtensionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


