/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FaxSmsTarget struct for FaxSmsTarget
type FaxSmsTarget struct {
	Id *string `json:"id,omitempty"`
	Number *string `json:"number,omitempty"`
	Direction *string `json:"direction,omitempty"`
}

// NewFaxSmsTarget instantiates a new FaxSmsTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaxSmsTarget() *FaxSmsTarget {
	this := FaxSmsTarget{}
	return &this
}

// NewFaxSmsTargetWithDefaults instantiates a new FaxSmsTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaxSmsTargetWithDefaults() *FaxSmsTarget {
	this := FaxSmsTarget{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FaxSmsTarget) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxSmsTarget) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FaxSmsTarget) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FaxSmsTarget) SetId(v string) {
	o.Id = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *FaxSmsTarget) GetNumber() string {
	if o == nil || o.Number == nil {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxSmsTarget) GetNumberOk() (*string, bool) {
	if o == nil || o.Number == nil {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *FaxSmsTarget) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *FaxSmsTarget) SetNumber(v string) {
	o.Number = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *FaxSmsTarget) GetDirection() string {
	if o == nil || o.Direction == nil {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxSmsTarget) GetDirectionOk() (*string, bool) {
	if o == nil || o.Direction == nil {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *FaxSmsTarget) HasDirection() bool {
	if o != nil && o.Direction != nil {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *FaxSmsTarget) SetDirection(v string) {
	o.Direction = &v
}

func (o FaxSmsTarget) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Number != nil {
		toSerialize["number"] = o.Number
	}
	if o.Direction != nil {
		toSerialize["direction"] = o.Direction
	}
	return json.Marshal(toSerialize)
}

type NullableFaxSmsTarget struct {
	value *FaxSmsTarget
	isSet bool
}

func (v NullableFaxSmsTarget) Get() *FaxSmsTarget {
	return v.value
}

func (v *NullableFaxSmsTarget) Set(val *FaxSmsTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableFaxSmsTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableFaxSmsTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaxSmsTarget(val *FaxSmsTarget) *NullableFaxSmsTarget {
	return &NullableFaxSmsTarget{value: val, isSet: true}
}

func (v NullableFaxSmsTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaxSmsTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


