/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ReportTarget struct for ReportTarget
type ReportTarget struct {
	Id *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
}

// NewReportTarget instantiates a new ReportTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportTarget() *ReportTarget {
	this := ReportTarget{}
	return &this
}

// NewReportTargetWithDefaults instantiates a new ReportTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportTargetWithDefaults() *ReportTarget {
	this := ReportTarget{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReportTarget) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportTarget) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReportTarget) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReportTarget) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ReportTarget) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportTarget) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ReportTarget) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ReportTarget) SetEmail(v string) {
	o.Email = &v
}

func (o ReportTarget) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableReportTarget struct {
	value *ReportTarget
	isSet bool
}

func (v NullableReportTarget) Get() *ReportTarget {
	return v.value
}

func (v *NullableReportTarget) Set(val *ReportTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableReportTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableReportTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportTarget(val *ReportTarget) *NullableReportTarget {
	return &NullableReportTarget{value: val, isSet: true}
}

func (v NullableReportTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


