/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PhonelineSipgateIoResponse struct for PhonelineSipgateIoResponse
type PhonelineSipgateIoResponse struct {
	IncomingActive *bool `json:"incomingActive,omitempty"`
	OutgoingActive *bool `json:"outgoingActive,omitempty"`
	IncomingUrl *string `json:"incomingUrl,omitempty"`
	OutgoingUrl *string `json:"outgoingUrl,omitempty"`
	Log *bool `json:"log,omitempty"`
	Certificate *string `json:"certificate,omitempty"`
	AllowSelfSigned *bool `json:"allowSelfSigned,omitempty"`
}

// NewPhonelineSipgateIoResponse instantiates a new PhonelineSipgateIoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhonelineSipgateIoResponse() *PhonelineSipgateIoResponse {
	this := PhonelineSipgateIoResponse{}
	var incomingActive bool = false
	this.IncomingActive = &incomingActive
	var outgoingActive bool = false
	this.OutgoingActive = &outgoingActive
	var log bool = false
	this.Log = &log
	var allowSelfSigned bool = false
	this.AllowSelfSigned = &allowSelfSigned
	return &this
}

// NewPhonelineSipgateIoResponseWithDefaults instantiates a new PhonelineSipgateIoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhonelineSipgateIoResponseWithDefaults() *PhonelineSipgateIoResponse {
	this := PhonelineSipgateIoResponse{}
	var incomingActive bool = false
	this.IncomingActive = &incomingActive
	var outgoingActive bool = false
	this.OutgoingActive = &outgoingActive
	var log bool = false
	this.Log = &log
	var allowSelfSigned bool = false
	this.AllowSelfSigned = &allowSelfSigned
	return &this
}

// GetIncomingActive returns the IncomingActive field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetIncomingActive() bool {
	if o == nil || o.IncomingActive == nil {
		var ret bool
		return ret
	}
	return *o.IncomingActive
}

// GetIncomingActiveOk returns a tuple with the IncomingActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetIncomingActiveOk() (*bool, bool) {
	if o == nil || o.IncomingActive == nil {
		return nil, false
	}
	return o.IncomingActive, true
}

// HasIncomingActive returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasIncomingActive() bool {
	if o != nil && o.IncomingActive != nil {
		return true
	}

	return false
}

// SetIncomingActive gets a reference to the given bool and assigns it to the IncomingActive field.
func (o *PhonelineSipgateIoResponse) SetIncomingActive(v bool) {
	o.IncomingActive = &v
}

// GetOutgoingActive returns the OutgoingActive field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetOutgoingActive() bool {
	if o == nil || o.OutgoingActive == nil {
		var ret bool
		return ret
	}
	return *o.OutgoingActive
}

// GetOutgoingActiveOk returns a tuple with the OutgoingActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetOutgoingActiveOk() (*bool, bool) {
	if o == nil || o.OutgoingActive == nil {
		return nil, false
	}
	return o.OutgoingActive, true
}

// HasOutgoingActive returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasOutgoingActive() bool {
	if o != nil && o.OutgoingActive != nil {
		return true
	}

	return false
}

// SetOutgoingActive gets a reference to the given bool and assigns it to the OutgoingActive field.
func (o *PhonelineSipgateIoResponse) SetOutgoingActive(v bool) {
	o.OutgoingActive = &v
}

// GetIncomingUrl returns the IncomingUrl field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetIncomingUrl() string {
	if o == nil || o.IncomingUrl == nil {
		var ret string
		return ret
	}
	return *o.IncomingUrl
}

// GetIncomingUrlOk returns a tuple with the IncomingUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetIncomingUrlOk() (*string, bool) {
	if o == nil || o.IncomingUrl == nil {
		return nil, false
	}
	return o.IncomingUrl, true
}

// HasIncomingUrl returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasIncomingUrl() bool {
	if o != nil && o.IncomingUrl != nil {
		return true
	}

	return false
}

// SetIncomingUrl gets a reference to the given string and assigns it to the IncomingUrl field.
func (o *PhonelineSipgateIoResponse) SetIncomingUrl(v string) {
	o.IncomingUrl = &v
}

// GetOutgoingUrl returns the OutgoingUrl field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetOutgoingUrl() string {
	if o == nil || o.OutgoingUrl == nil {
		var ret string
		return ret
	}
	return *o.OutgoingUrl
}

// GetOutgoingUrlOk returns a tuple with the OutgoingUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetOutgoingUrlOk() (*string, bool) {
	if o == nil || o.OutgoingUrl == nil {
		return nil, false
	}
	return o.OutgoingUrl, true
}

// HasOutgoingUrl returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasOutgoingUrl() bool {
	if o != nil && o.OutgoingUrl != nil {
		return true
	}

	return false
}

// SetOutgoingUrl gets a reference to the given string and assigns it to the OutgoingUrl field.
func (o *PhonelineSipgateIoResponse) SetOutgoingUrl(v string) {
	o.OutgoingUrl = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetLog() bool {
	if o == nil || o.Log == nil {
		var ret bool
		return ret
	}
	return *o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetLogOk() (*bool, bool) {
	if o == nil || o.Log == nil {
		return nil, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasLog() bool {
	if o != nil && o.Log != nil {
		return true
	}

	return false
}

// SetLog gets a reference to the given bool and assigns it to the Log field.
func (o *PhonelineSipgateIoResponse) SetLog(v bool) {
	o.Log = &v
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetCertificate() string {
	if o == nil || o.Certificate == nil {
		var ret string
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetCertificateOk() (*string, bool) {
	if o == nil || o.Certificate == nil {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasCertificate() bool {
	if o != nil && o.Certificate != nil {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given string and assigns it to the Certificate field.
func (o *PhonelineSipgateIoResponse) SetCertificate(v string) {
	o.Certificate = &v
}

// GetAllowSelfSigned returns the AllowSelfSigned field value if set, zero value otherwise.
func (o *PhonelineSipgateIoResponse) GetAllowSelfSigned() bool {
	if o == nil || o.AllowSelfSigned == nil {
		var ret bool
		return ret
	}
	return *o.AllowSelfSigned
}

// GetAllowSelfSignedOk returns a tuple with the AllowSelfSigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineSipgateIoResponse) GetAllowSelfSignedOk() (*bool, bool) {
	if o == nil || o.AllowSelfSigned == nil {
		return nil, false
	}
	return o.AllowSelfSigned, true
}

// HasAllowSelfSigned returns a boolean if a field has been set.
func (o *PhonelineSipgateIoResponse) HasAllowSelfSigned() bool {
	if o != nil && o.AllowSelfSigned != nil {
		return true
	}

	return false
}

// SetAllowSelfSigned gets a reference to the given bool and assigns it to the AllowSelfSigned field.
func (o *PhonelineSipgateIoResponse) SetAllowSelfSigned(v bool) {
	o.AllowSelfSigned = &v
}

func (o PhonelineSipgateIoResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncomingActive != nil {
		toSerialize["incomingActive"] = o.IncomingActive
	}
	if o.OutgoingActive != nil {
		toSerialize["outgoingActive"] = o.OutgoingActive
	}
	if o.IncomingUrl != nil {
		toSerialize["incomingUrl"] = o.IncomingUrl
	}
	if o.OutgoingUrl != nil {
		toSerialize["outgoingUrl"] = o.OutgoingUrl
	}
	if o.Log != nil {
		toSerialize["log"] = o.Log
	}
	if o.Certificate != nil {
		toSerialize["certificate"] = o.Certificate
	}
	if o.AllowSelfSigned != nil {
		toSerialize["allowSelfSigned"] = o.AllowSelfSigned
	}
	return json.Marshal(toSerialize)
}

type NullablePhonelineSipgateIoResponse struct {
	value *PhonelineSipgateIoResponse
	isSet bool
}

func (v NullablePhonelineSipgateIoResponse) Get() *PhonelineSipgateIoResponse {
	return v.value
}

func (v *NullablePhonelineSipgateIoResponse) Set(val *PhonelineSipgateIoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePhonelineSipgateIoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePhonelineSipgateIoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhonelineSipgateIoResponse(val *PhonelineSipgateIoResponse) *NullablePhonelineSipgateIoResponse {
	return &NullablePhonelineSipgateIoResponse{value: val, isSet: true}
}

func (v NullablePhonelineSipgateIoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhonelineSipgateIoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


