/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountVerificationRequest struct for AccountVerificationRequest
type AccountVerificationRequest struct {
	VerificationCode string `json:"verificationCode"`
}

// NewAccountVerificationRequest instantiates a new AccountVerificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountVerificationRequest(verificationCode string) *AccountVerificationRequest {
	this := AccountVerificationRequest{}
	this.VerificationCode = verificationCode
	return &this
}

// NewAccountVerificationRequestWithDefaults instantiates a new AccountVerificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountVerificationRequestWithDefaults() *AccountVerificationRequest {
	this := AccountVerificationRequest{}
	return &this
}

// GetVerificationCode returns the VerificationCode field value
func (o *AccountVerificationRequest) GetVerificationCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationCode
}

// GetVerificationCodeOk returns a tuple with the VerificationCode field value
// and a boolean to check if the value has been set.
func (o *AccountVerificationRequest) GetVerificationCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationCode, true
}

// SetVerificationCode sets field value
func (o *AccountVerificationRequest) SetVerificationCode(v string) {
	o.VerificationCode = v
}

func (o AccountVerificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["verificationCode"] = o.VerificationCode
	}
	return json.Marshal(toSerialize)
}

type NullableAccountVerificationRequest struct {
	value *AccountVerificationRequest
	isSet bool
}

func (v NullableAccountVerificationRequest) Get() *AccountVerificationRequest {
	return v.value
}

func (v *NullableAccountVerificationRequest) Set(val *AccountVerificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountVerificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountVerificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountVerificationRequest(val *AccountVerificationRequest) *NullableAccountVerificationRequest {
	return &NullableAccountVerificationRequest{value: val, isSet: true}
}

func (v NullableAccountVerificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountVerificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


