/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TariffAnnouncementResponse struct for TariffAnnouncementResponse
type TariffAnnouncementResponse struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewTariffAnnouncementResponse instantiates a new TariffAnnouncementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTariffAnnouncementResponse() *TariffAnnouncementResponse {
	this := TariffAnnouncementResponse{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewTariffAnnouncementResponseWithDefaults instantiates a new TariffAnnouncementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTariffAnnouncementResponseWithDefaults() *TariffAnnouncementResponse {
	this := TariffAnnouncementResponse{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TariffAnnouncementResponse) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TariffAnnouncementResponse) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TariffAnnouncementResponse) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TariffAnnouncementResponse) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o TariffAnnouncementResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableTariffAnnouncementResponse struct {
	value *TariffAnnouncementResponse
	isSet bool
}

func (v NullableTariffAnnouncementResponse) Get() *TariffAnnouncementResponse {
	return v.value
}

func (v *NullableTariffAnnouncementResponse) Set(val *TariffAnnouncementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTariffAnnouncementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTariffAnnouncementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTariffAnnouncementResponse(val *TariffAnnouncementResponse) *NullableTariffAnnouncementResponse {
	return &NullableTariffAnnouncementResponse{value: val, isSet: true}
}

func (v NullableTariffAnnouncementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTariffAnnouncementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


