/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ChangeNumberSettingsRequest struct for ChangeNumberSettingsRequest
type ChangeNumberSettingsRequest struct {
	EndpointId *string `json:"endpointId,omitempty"`
	ReleaseForMnp *bool `json:"releaseForMnp,omitempty"`
	QuickDial *bool `json:"quickDial,omitempty"`
}

// NewChangeNumberSettingsRequest instantiates a new ChangeNumberSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeNumberSettingsRequest() *ChangeNumberSettingsRequest {
	this := ChangeNumberSettingsRequest{}
	var releaseForMnp bool = false
	this.ReleaseForMnp = &releaseForMnp
	var quickDial bool = false
	this.QuickDial = &quickDial
	return &this
}

// NewChangeNumberSettingsRequestWithDefaults instantiates a new ChangeNumberSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeNumberSettingsRequestWithDefaults() *ChangeNumberSettingsRequest {
	this := ChangeNumberSettingsRequest{}
	var releaseForMnp bool = false
	this.ReleaseForMnp = &releaseForMnp
	var quickDial bool = false
	this.QuickDial = &quickDial
	return &this
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *ChangeNumberSettingsRequest) GetEndpointId() string {
	if o == nil || o.EndpointId == nil {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeNumberSettingsRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil || o.EndpointId == nil {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *ChangeNumberSettingsRequest) HasEndpointId() bool {
	if o != nil && o.EndpointId != nil {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *ChangeNumberSettingsRequest) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetReleaseForMnp returns the ReleaseForMnp field value if set, zero value otherwise.
func (o *ChangeNumberSettingsRequest) GetReleaseForMnp() bool {
	if o == nil || o.ReleaseForMnp == nil {
		var ret bool
		return ret
	}
	return *o.ReleaseForMnp
}

// GetReleaseForMnpOk returns a tuple with the ReleaseForMnp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeNumberSettingsRequest) GetReleaseForMnpOk() (*bool, bool) {
	if o == nil || o.ReleaseForMnp == nil {
		return nil, false
	}
	return o.ReleaseForMnp, true
}

// HasReleaseForMnp returns a boolean if a field has been set.
func (o *ChangeNumberSettingsRequest) HasReleaseForMnp() bool {
	if o != nil && o.ReleaseForMnp != nil {
		return true
	}

	return false
}

// SetReleaseForMnp gets a reference to the given bool and assigns it to the ReleaseForMnp field.
func (o *ChangeNumberSettingsRequest) SetReleaseForMnp(v bool) {
	o.ReleaseForMnp = &v
}

// GetQuickDial returns the QuickDial field value if set, zero value otherwise.
func (o *ChangeNumberSettingsRequest) GetQuickDial() bool {
	if o == nil || o.QuickDial == nil {
		var ret bool
		return ret
	}
	return *o.QuickDial
}

// GetQuickDialOk returns a tuple with the QuickDial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeNumberSettingsRequest) GetQuickDialOk() (*bool, bool) {
	if o == nil || o.QuickDial == nil {
		return nil, false
	}
	return o.QuickDial, true
}

// HasQuickDial returns a boolean if a field has been set.
func (o *ChangeNumberSettingsRequest) HasQuickDial() bool {
	if o != nil && o.QuickDial != nil {
		return true
	}

	return false
}

// SetQuickDial gets a reference to the given bool and assigns it to the QuickDial field.
func (o *ChangeNumberSettingsRequest) SetQuickDial(v bool) {
	o.QuickDial = &v
}

func (o ChangeNumberSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EndpointId != nil {
		toSerialize["endpointId"] = o.EndpointId
	}
	if o.ReleaseForMnp != nil {
		toSerialize["releaseForMnp"] = o.ReleaseForMnp
	}
	if o.QuickDial != nil {
		toSerialize["quickDial"] = o.QuickDial
	}
	return json.Marshal(toSerialize)
}

type NullableChangeNumberSettingsRequest struct {
	value *ChangeNumberSettingsRequest
	isSet bool
}

func (v NullableChangeNumberSettingsRequest) Get() *ChangeNumberSettingsRequest {
	return v.value
}

func (v *NullableChangeNumberSettingsRequest) Set(val *ChangeNumberSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeNumberSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeNumberSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeNumberSettingsRequest(val *ChangeNumberSettingsRequest) *NullableChangeNumberSettingsRequest {
	return &NullableChangeNumberSettingsRequest{value: val, isSet: true}
}

func (v NullableChangeNumberSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeNumberSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


