/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GroupFaxlineResponse struct for GroupFaxlineResponse
type GroupFaxlineResponse struct {
	Id *string `json:"id,omitempty"`
	Alias *string `json:"alias,omitempty"`
	Tagline *string `json:"tagline,omitempty"`
	CanSend *bool `json:"canSend,omitempty"`
	CanReceive *bool `json:"canReceive,omitempty"`
	GroupId *string `json:"groupId,omitempty"`
}

// NewGroupFaxlineResponse instantiates a new GroupFaxlineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupFaxlineResponse() *GroupFaxlineResponse {
	this := GroupFaxlineResponse{}
	var canSend bool = false
	this.CanSend = &canSend
	var canReceive bool = false
	this.CanReceive = &canReceive
	return &this
}

// NewGroupFaxlineResponseWithDefaults instantiates a new GroupFaxlineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupFaxlineResponseWithDefaults() *GroupFaxlineResponse {
	this := GroupFaxlineResponse{}
	var canSend bool = false
	this.CanSend = &canSend
	var canReceive bool = false
	this.CanReceive = &canReceive
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GroupFaxlineResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFaxlineResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GroupFaxlineResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GroupFaxlineResponse) SetId(v string) {
	o.Id = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *GroupFaxlineResponse) GetAlias() string {
	if o == nil || o.Alias == nil {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFaxlineResponse) GetAliasOk() (*string, bool) {
	if o == nil || o.Alias == nil {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *GroupFaxlineResponse) HasAlias() bool {
	if o != nil && o.Alias != nil {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *GroupFaxlineResponse) SetAlias(v string) {
	o.Alias = &v
}

// GetTagline returns the Tagline field value if set, zero value otherwise.
func (o *GroupFaxlineResponse) GetTagline() string {
	if o == nil || o.Tagline == nil {
		var ret string
		return ret
	}
	return *o.Tagline
}

// GetTaglineOk returns a tuple with the Tagline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFaxlineResponse) GetTaglineOk() (*string, bool) {
	if o == nil || o.Tagline == nil {
		return nil, false
	}
	return o.Tagline, true
}

// HasTagline returns a boolean if a field has been set.
func (o *GroupFaxlineResponse) HasTagline() bool {
	if o != nil && o.Tagline != nil {
		return true
	}

	return false
}

// SetTagline gets a reference to the given string and assigns it to the Tagline field.
func (o *GroupFaxlineResponse) SetTagline(v string) {
	o.Tagline = &v
}

// GetCanSend returns the CanSend field value if set, zero value otherwise.
func (o *GroupFaxlineResponse) GetCanSend() bool {
	if o == nil || o.CanSend == nil {
		var ret bool
		return ret
	}
	return *o.CanSend
}

// GetCanSendOk returns a tuple with the CanSend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFaxlineResponse) GetCanSendOk() (*bool, bool) {
	if o == nil || o.CanSend == nil {
		return nil, false
	}
	return o.CanSend, true
}

// HasCanSend returns a boolean if a field has been set.
func (o *GroupFaxlineResponse) HasCanSend() bool {
	if o != nil && o.CanSend != nil {
		return true
	}

	return false
}

// SetCanSend gets a reference to the given bool and assigns it to the CanSend field.
func (o *GroupFaxlineResponse) SetCanSend(v bool) {
	o.CanSend = &v
}

// GetCanReceive returns the CanReceive field value if set, zero value otherwise.
func (o *GroupFaxlineResponse) GetCanReceive() bool {
	if o == nil || o.CanReceive == nil {
		var ret bool
		return ret
	}
	return *o.CanReceive
}

// GetCanReceiveOk returns a tuple with the CanReceive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFaxlineResponse) GetCanReceiveOk() (*bool, bool) {
	if o == nil || o.CanReceive == nil {
		return nil, false
	}
	return o.CanReceive, true
}

// HasCanReceive returns a boolean if a field has been set.
func (o *GroupFaxlineResponse) HasCanReceive() bool {
	if o != nil && o.CanReceive != nil {
		return true
	}

	return false
}

// SetCanReceive gets a reference to the given bool and assigns it to the CanReceive field.
func (o *GroupFaxlineResponse) SetCanReceive(v bool) {
	o.CanReceive = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *GroupFaxlineResponse) GetGroupId() string {
	if o == nil || o.GroupId == nil {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFaxlineResponse) GetGroupIdOk() (*string, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *GroupFaxlineResponse) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *GroupFaxlineResponse) SetGroupId(v string) {
	o.GroupId = &v
}

func (o GroupFaxlineResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Alias != nil {
		toSerialize["alias"] = o.Alias
	}
	if o.Tagline != nil {
		toSerialize["tagline"] = o.Tagline
	}
	if o.CanSend != nil {
		toSerialize["canSend"] = o.CanSend
	}
	if o.CanReceive != nil {
		toSerialize["canReceive"] = o.CanReceive
	}
	if o.GroupId != nil {
		toSerialize["groupId"] = o.GroupId
	}
	return json.Marshal(toSerialize)
}

type NullableGroupFaxlineResponse struct {
	value *GroupFaxlineResponse
	isSet bool
}

func (v NullableGroupFaxlineResponse) Get() *GroupFaxlineResponse {
	return v.value
}

func (v *NullableGroupFaxlineResponse) Set(val *GroupFaxlineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupFaxlineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupFaxlineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupFaxlineResponse(val *GroupFaxlineResponse) *NullableGroupFaxlineResponse {
	return &NullableGroupFaxlineResponse{value: val, isSet: true}
}

func (v NullableGroupFaxlineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupFaxlineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


