/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PhonelineVoicemailsResponse struct for PhonelineVoicemailsResponse
type PhonelineVoicemailsResponse struct {
	Items []PhonelineVoicemailResponse `json:"items,omitempty"`
}

// NewPhonelineVoicemailsResponse instantiates a new PhonelineVoicemailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhonelineVoicemailsResponse() *PhonelineVoicemailsResponse {
	this := PhonelineVoicemailsResponse{}
	return &this
}

// NewPhonelineVoicemailsResponseWithDefaults instantiates a new PhonelineVoicemailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhonelineVoicemailsResponseWithDefaults() *PhonelineVoicemailsResponse {
	this := PhonelineVoicemailsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PhonelineVoicemailsResponse) GetItems() []PhonelineVoicemailResponse {
	if o == nil || o.Items == nil {
		var ret []PhonelineVoicemailResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhonelineVoicemailsResponse) GetItemsOk() ([]PhonelineVoicemailResponse, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PhonelineVoicemailsResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PhonelineVoicemailResponse and assigns it to the Items field.
func (o *PhonelineVoicemailsResponse) SetItems(v []PhonelineVoicemailResponse) {
	o.Items = v
}

func (o PhonelineVoicemailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullablePhonelineVoicemailsResponse struct {
	value *PhonelineVoicemailsResponse
	isSet bool
}

func (v NullablePhonelineVoicemailsResponse) Get() *PhonelineVoicemailsResponse {
	return v.value
}

func (v *NullablePhonelineVoicemailsResponse) Set(val *PhonelineVoicemailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePhonelineVoicemailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePhonelineVoicemailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhonelineVoicemailsResponse(val *PhonelineVoicemailsResponse) *NullablePhonelineVoicemailsResponse {
	return &NullablePhonelineVoicemailsResponse{value: val, isSet: true}
}

func (v NullablePhonelineVoicemailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhonelineVoicemailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


