/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PropertiesResponse struct for PropertiesResponse
type PropertiesResponse struct {
	IdentityVerificationRequired *bool `json:"identityVerificationRequired,omitempty"`
	VerificationLetterCodeRequired *bool `json:"verificationLetterCodeRequired,omitempty"`
	ShowSipCredentials *bool `json:"showSipCredentials,omitempty"`
	ShowRegisterDndOption *bool `json:"showRegisterDndOption,omitempty"`
	ShowDisplaySingleLineOption *bool `json:"showDisplaySingleLineOption,omitempty"`
	ShowClick2DialButton *bool `json:"showClick2DialButton,omitempty"`
	ShowVerificationLetter *bool `json:"showVerificationLetter,omitempty"`
	HasDedicatedAdminArea *bool `json:"hasDedicatedAdminArea,omitempty"`
	ShowSimRelevantOptions *bool `json:"showSimRelevantOptions,omitempty"`
	ShowESimOptions *bool `json:"showESimOptions,omitempty"`
	ShowEventTimeToLiveHint *bool `json:"showEventTimeToLiveHint,omitempty"`
	ShowNettoPrices *bool `json:"showNettoPrices,omitempty"`
	ShowBasicLogo *bool `json:"showBasicLogo,omitempty"`
	ShowSimquadratLogo *bool `json:"showSimquadratLogo,omitempty"`
	IdentityVerificationRequiredForMobile *bool `json:"identityVerificationRequiredForMobile,omitempty"`
	ChatbotHuman *bool `json:"chatbotHuman,omitempty"`
	ChatbotUsingInformalLanguage *bool `json:"chatbotUsingInformalLanguage,omitempty"`
	MultiSimProduct *bool `json:"multiSimProduct,omitempty"`
	ProductWithoutBaseFee *bool `json:"productWithoutBaseFee,omitempty"`
	VoipOnlyProduct *bool `json:"voipOnlyProduct,omitempty"`
	MobileOnlyProduct *bool `json:"mobileOnlyProduct,omitempty"`
}

// NewPropertiesResponse instantiates a new PropertiesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPropertiesResponse() *PropertiesResponse {
	this := PropertiesResponse{}
	var identityVerificationRequired bool = false
	this.IdentityVerificationRequired = &identityVerificationRequired
	var verificationLetterCodeRequired bool = false
	this.VerificationLetterCodeRequired = &verificationLetterCodeRequired
	var showSipCredentials bool = false
	this.ShowSipCredentials = &showSipCredentials
	var showRegisterDndOption bool = false
	this.ShowRegisterDndOption = &showRegisterDndOption
	var showDisplaySingleLineOption bool = false
	this.ShowDisplaySingleLineOption = &showDisplaySingleLineOption
	var showClick2DialButton bool = false
	this.ShowClick2DialButton = &showClick2DialButton
	var showVerificationLetter bool = false
	this.ShowVerificationLetter = &showVerificationLetter
	var hasDedicatedAdminArea bool = false
	this.HasDedicatedAdminArea = &hasDedicatedAdminArea
	var showSimRelevantOptions bool = false
	this.ShowSimRelevantOptions = &showSimRelevantOptions
	var showESimOptions bool = false
	this.ShowESimOptions = &showESimOptions
	var showEventTimeToLiveHint bool = false
	this.ShowEventTimeToLiveHint = &showEventTimeToLiveHint
	var showNettoPrices bool = false
	this.ShowNettoPrices = &showNettoPrices
	var showBasicLogo bool = false
	this.ShowBasicLogo = &showBasicLogo
	var showSimquadratLogo bool = false
	this.ShowSimquadratLogo = &showSimquadratLogo
	var identityVerificationRequiredForMobile bool = false
	this.IdentityVerificationRequiredForMobile = &identityVerificationRequiredForMobile
	var chatbotHuman bool = false
	this.ChatbotHuman = &chatbotHuman
	var chatbotUsingInformalLanguage bool = false
	this.ChatbotUsingInformalLanguage = &chatbotUsingInformalLanguage
	var multiSimProduct bool = false
	this.MultiSimProduct = &multiSimProduct
	var productWithoutBaseFee bool = false
	this.ProductWithoutBaseFee = &productWithoutBaseFee
	var voipOnlyProduct bool = false
	this.VoipOnlyProduct = &voipOnlyProduct
	var mobileOnlyProduct bool = false
	this.MobileOnlyProduct = &mobileOnlyProduct
	return &this
}

// NewPropertiesResponseWithDefaults instantiates a new PropertiesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertiesResponseWithDefaults() *PropertiesResponse {
	this := PropertiesResponse{}
	var identityVerificationRequired bool = false
	this.IdentityVerificationRequired = &identityVerificationRequired
	var verificationLetterCodeRequired bool = false
	this.VerificationLetterCodeRequired = &verificationLetterCodeRequired
	var showSipCredentials bool = false
	this.ShowSipCredentials = &showSipCredentials
	var showRegisterDndOption bool = false
	this.ShowRegisterDndOption = &showRegisterDndOption
	var showDisplaySingleLineOption bool = false
	this.ShowDisplaySingleLineOption = &showDisplaySingleLineOption
	var showClick2DialButton bool = false
	this.ShowClick2DialButton = &showClick2DialButton
	var showVerificationLetter bool = false
	this.ShowVerificationLetter = &showVerificationLetter
	var hasDedicatedAdminArea bool = false
	this.HasDedicatedAdminArea = &hasDedicatedAdminArea
	var showSimRelevantOptions bool = false
	this.ShowSimRelevantOptions = &showSimRelevantOptions
	var showESimOptions bool = false
	this.ShowESimOptions = &showESimOptions
	var showEventTimeToLiveHint bool = false
	this.ShowEventTimeToLiveHint = &showEventTimeToLiveHint
	var showNettoPrices bool = false
	this.ShowNettoPrices = &showNettoPrices
	var showBasicLogo bool = false
	this.ShowBasicLogo = &showBasicLogo
	var showSimquadratLogo bool = false
	this.ShowSimquadratLogo = &showSimquadratLogo
	var identityVerificationRequiredForMobile bool = false
	this.IdentityVerificationRequiredForMobile = &identityVerificationRequiredForMobile
	var chatbotHuman bool = false
	this.ChatbotHuman = &chatbotHuman
	var chatbotUsingInformalLanguage bool = false
	this.ChatbotUsingInformalLanguage = &chatbotUsingInformalLanguage
	var multiSimProduct bool = false
	this.MultiSimProduct = &multiSimProduct
	var productWithoutBaseFee bool = false
	this.ProductWithoutBaseFee = &productWithoutBaseFee
	var voipOnlyProduct bool = false
	this.VoipOnlyProduct = &voipOnlyProduct
	var mobileOnlyProduct bool = false
	this.MobileOnlyProduct = &mobileOnlyProduct
	return &this
}

// GetIdentityVerificationRequired returns the IdentityVerificationRequired field value if set, zero value otherwise.
func (o *PropertiesResponse) GetIdentityVerificationRequired() bool {
	if o == nil || o.IdentityVerificationRequired == nil {
		var ret bool
		return ret
	}
	return *o.IdentityVerificationRequired
}

// GetIdentityVerificationRequiredOk returns a tuple with the IdentityVerificationRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetIdentityVerificationRequiredOk() (*bool, bool) {
	if o == nil || o.IdentityVerificationRequired == nil {
		return nil, false
	}
	return o.IdentityVerificationRequired, true
}

// HasIdentityVerificationRequired returns a boolean if a field has been set.
func (o *PropertiesResponse) HasIdentityVerificationRequired() bool {
	if o != nil && o.IdentityVerificationRequired != nil {
		return true
	}

	return false
}

// SetIdentityVerificationRequired gets a reference to the given bool and assigns it to the IdentityVerificationRequired field.
func (o *PropertiesResponse) SetIdentityVerificationRequired(v bool) {
	o.IdentityVerificationRequired = &v
}

// GetVerificationLetterCodeRequired returns the VerificationLetterCodeRequired field value if set, zero value otherwise.
func (o *PropertiesResponse) GetVerificationLetterCodeRequired() bool {
	if o == nil || o.VerificationLetterCodeRequired == nil {
		var ret bool
		return ret
	}
	return *o.VerificationLetterCodeRequired
}

// GetVerificationLetterCodeRequiredOk returns a tuple with the VerificationLetterCodeRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetVerificationLetterCodeRequiredOk() (*bool, bool) {
	if o == nil || o.VerificationLetterCodeRequired == nil {
		return nil, false
	}
	return o.VerificationLetterCodeRequired, true
}

// HasVerificationLetterCodeRequired returns a boolean if a field has been set.
func (o *PropertiesResponse) HasVerificationLetterCodeRequired() bool {
	if o != nil && o.VerificationLetterCodeRequired != nil {
		return true
	}

	return false
}

// SetVerificationLetterCodeRequired gets a reference to the given bool and assigns it to the VerificationLetterCodeRequired field.
func (o *PropertiesResponse) SetVerificationLetterCodeRequired(v bool) {
	o.VerificationLetterCodeRequired = &v
}

// GetShowSipCredentials returns the ShowSipCredentials field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowSipCredentials() bool {
	if o == nil || o.ShowSipCredentials == nil {
		var ret bool
		return ret
	}
	return *o.ShowSipCredentials
}

// GetShowSipCredentialsOk returns a tuple with the ShowSipCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowSipCredentialsOk() (*bool, bool) {
	if o == nil || o.ShowSipCredentials == nil {
		return nil, false
	}
	return o.ShowSipCredentials, true
}

// HasShowSipCredentials returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowSipCredentials() bool {
	if o != nil && o.ShowSipCredentials != nil {
		return true
	}

	return false
}

// SetShowSipCredentials gets a reference to the given bool and assigns it to the ShowSipCredentials field.
func (o *PropertiesResponse) SetShowSipCredentials(v bool) {
	o.ShowSipCredentials = &v
}

// GetShowRegisterDndOption returns the ShowRegisterDndOption field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowRegisterDndOption() bool {
	if o == nil || o.ShowRegisterDndOption == nil {
		var ret bool
		return ret
	}
	return *o.ShowRegisterDndOption
}

// GetShowRegisterDndOptionOk returns a tuple with the ShowRegisterDndOption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowRegisterDndOptionOk() (*bool, bool) {
	if o == nil || o.ShowRegisterDndOption == nil {
		return nil, false
	}
	return o.ShowRegisterDndOption, true
}

// HasShowRegisterDndOption returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowRegisterDndOption() bool {
	if o != nil && o.ShowRegisterDndOption != nil {
		return true
	}

	return false
}

// SetShowRegisterDndOption gets a reference to the given bool and assigns it to the ShowRegisterDndOption field.
func (o *PropertiesResponse) SetShowRegisterDndOption(v bool) {
	o.ShowRegisterDndOption = &v
}

// GetShowDisplaySingleLineOption returns the ShowDisplaySingleLineOption field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowDisplaySingleLineOption() bool {
	if o == nil || o.ShowDisplaySingleLineOption == nil {
		var ret bool
		return ret
	}
	return *o.ShowDisplaySingleLineOption
}

// GetShowDisplaySingleLineOptionOk returns a tuple with the ShowDisplaySingleLineOption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowDisplaySingleLineOptionOk() (*bool, bool) {
	if o == nil || o.ShowDisplaySingleLineOption == nil {
		return nil, false
	}
	return o.ShowDisplaySingleLineOption, true
}

// HasShowDisplaySingleLineOption returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowDisplaySingleLineOption() bool {
	if o != nil && o.ShowDisplaySingleLineOption != nil {
		return true
	}

	return false
}

// SetShowDisplaySingleLineOption gets a reference to the given bool and assigns it to the ShowDisplaySingleLineOption field.
func (o *PropertiesResponse) SetShowDisplaySingleLineOption(v bool) {
	o.ShowDisplaySingleLineOption = &v
}

// GetShowClick2DialButton returns the ShowClick2DialButton field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowClick2DialButton() bool {
	if o == nil || o.ShowClick2DialButton == nil {
		var ret bool
		return ret
	}
	return *o.ShowClick2DialButton
}

// GetShowClick2DialButtonOk returns a tuple with the ShowClick2DialButton field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowClick2DialButtonOk() (*bool, bool) {
	if o == nil || o.ShowClick2DialButton == nil {
		return nil, false
	}
	return o.ShowClick2DialButton, true
}

// HasShowClick2DialButton returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowClick2DialButton() bool {
	if o != nil && o.ShowClick2DialButton != nil {
		return true
	}

	return false
}

// SetShowClick2DialButton gets a reference to the given bool and assigns it to the ShowClick2DialButton field.
func (o *PropertiesResponse) SetShowClick2DialButton(v bool) {
	o.ShowClick2DialButton = &v
}

// GetShowVerificationLetter returns the ShowVerificationLetter field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowVerificationLetter() bool {
	if o == nil || o.ShowVerificationLetter == nil {
		var ret bool
		return ret
	}
	return *o.ShowVerificationLetter
}

// GetShowVerificationLetterOk returns a tuple with the ShowVerificationLetter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowVerificationLetterOk() (*bool, bool) {
	if o == nil || o.ShowVerificationLetter == nil {
		return nil, false
	}
	return o.ShowVerificationLetter, true
}

// HasShowVerificationLetter returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowVerificationLetter() bool {
	if o != nil && o.ShowVerificationLetter != nil {
		return true
	}

	return false
}

// SetShowVerificationLetter gets a reference to the given bool and assigns it to the ShowVerificationLetter field.
func (o *PropertiesResponse) SetShowVerificationLetter(v bool) {
	o.ShowVerificationLetter = &v
}

// GetHasDedicatedAdminArea returns the HasDedicatedAdminArea field value if set, zero value otherwise.
func (o *PropertiesResponse) GetHasDedicatedAdminArea() bool {
	if o == nil || o.HasDedicatedAdminArea == nil {
		var ret bool
		return ret
	}
	return *o.HasDedicatedAdminArea
}

// GetHasDedicatedAdminAreaOk returns a tuple with the HasDedicatedAdminArea field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetHasDedicatedAdminAreaOk() (*bool, bool) {
	if o == nil || o.HasDedicatedAdminArea == nil {
		return nil, false
	}
	return o.HasDedicatedAdminArea, true
}

// HasHasDedicatedAdminArea returns a boolean if a field has been set.
func (o *PropertiesResponse) HasHasDedicatedAdminArea() bool {
	if o != nil && o.HasDedicatedAdminArea != nil {
		return true
	}

	return false
}

// SetHasDedicatedAdminArea gets a reference to the given bool and assigns it to the HasDedicatedAdminArea field.
func (o *PropertiesResponse) SetHasDedicatedAdminArea(v bool) {
	o.HasDedicatedAdminArea = &v
}

// GetShowSimRelevantOptions returns the ShowSimRelevantOptions field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowSimRelevantOptions() bool {
	if o == nil || o.ShowSimRelevantOptions == nil {
		var ret bool
		return ret
	}
	return *o.ShowSimRelevantOptions
}

// GetShowSimRelevantOptionsOk returns a tuple with the ShowSimRelevantOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowSimRelevantOptionsOk() (*bool, bool) {
	if o == nil || o.ShowSimRelevantOptions == nil {
		return nil, false
	}
	return o.ShowSimRelevantOptions, true
}

// HasShowSimRelevantOptions returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowSimRelevantOptions() bool {
	if o != nil && o.ShowSimRelevantOptions != nil {
		return true
	}

	return false
}

// SetShowSimRelevantOptions gets a reference to the given bool and assigns it to the ShowSimRelevantOptions field.
func (o *PropertiesResponse) SetShowSimRelevantOptions(v bool) {
	o.ShowSimRelevantOptions = &v
}

// GetShowESimOptions returns the ShowESimOptions field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowESimOptions() bool {
	if o == nil || o.ShowESimOptions == nil {
		var ret bool
		return ret
	}
	return *o.ShowESimOptions
}

// GetShowESimOptionsOk returns a tuple with the ShowESimOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowESimOptionsOk() (*bool, bool) {
	if o == nil || o.ShowESimOptions == nil {
		return nil, false
	}
	return o.ShowESimOptions, true
}

// HasShowESimOptions returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowESimOptions() bool {
	if o != nil && o.ShowESimOptions != nil {
		return true
	}

	return false
}

// SetShowESimOptions gets a reference to the given bool and assigns it to the ShowESimOptions field.
func (o *PropertiesResponse) SetShowESimOptions(v bool) {
	o.ShowESimOptions = &v
}

// GetShowEventTimeToLiveHint returns the ShowEventTimeToLiveHint field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowEventTimeToLiveHint() bool {
	if o == nil || o.ShowEventTimeToLiveHint == nil {
		var ret bool
		return ret
	}
	return *o.ShowEventTimeToLiveHint
}

// GetShowEventTimeToLiveHintOk returns a tuple with the ShowEventTimeToLiveHint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowEventTimeToLiveHintOk() (*bool, bool) {
	if o == nil || o.ShowEventTimeToLiveHint == nil {
		return nil, false
	}
	return o.ShowEventTimeToLiveHint, true
}

// HasShowEventTimeToLiveHint returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowEventTimeToLiveHint() bool {
	if o != nil && o.ShowEventTimeToLiveHint != nil {
		return true
	}

	return false
}

// SetShowEventTimeToLiveHint gets a reference to the given bool and assigns it to the ShowEventTimeToLiveHint field.
func (o *PropertiesResponse) SetShowEventTimeToLiveHint(v bool) {
	o.ShowEventTimeToLiveHint = &v
}

// GetShowNettoPrices returns the ShowNettoPrices field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowNettoPrices() bool {
	if o == nil || o.ShowNettoPrices == nil {
		var ret bool
		return ret
	}
	return *o.ShowNettoPrices
}

// GetShowNettoPricesOk returns a tuple with the ShowNettoPrices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowNettoPricesOk() (*bool, bool) {
	if o == nil || o.ShowNettoPrices == nil {
		return nil, false
	}
	return o.ShowNettoPrices, true
}

// HasShowNettoPrices returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowNettoPrices() bool {
	if o != nil && o.ShowNettoPrices != nil {
		return true
	}

	return false
}

// SetShowNettoPrices gets a reference to the given bool and assigns it to the ShowNettoPrices field.
func (o *PropertiesResponse) SetShowNettoPrices(v bool) {
	o.ShowNettoPrices = &v
}

// GetShowBasicLogo returns the ShowBasicLogo field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowBasicLogo() bool {
	if o == nil || o.ShowBasicLogo == nil {
		var ret bool
		return ret
	}
	return *o.ShowBasicLogo
}

// GetShowBasicLogoOk returns a tuple with the ShowBasicLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowBasicLogoOk() (*bool, bool) {
	if o == nil || o.ShowBasicLogo == nil {
		return nil, false
	}
	return o.ShowBasicLogo, true
}

// HasShowBasicLogo returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowBasicLogo() bool {
	if o != nil && o.ShowBasicLogo != nil {
		return true
	}

	return false
}

// SetShowBasicLogo gets a reference to the given bool and assigns it to the ShowBasicLogo field.
func (o *PropertiesResponse) SetShowBasicLogo(v bool) {
	o.ShowBasicLogo = &v
}

// GetShowSimquadratLogo returns the ShowSimquadratLogo field value if set, zero value otherwise.
func (o *PropertiesResponse) GetShowSimquadratLogo() bool {
	if o == nil || o.ShowSimquadratLogo == nil {
		var ret bool
		return ret
	}
	return *o.ShowSimquadratLogo
}

// GetShowSimquadratLogoOk returns a tuple with the ShowSimquadratLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetShowSimquadratLogoOk() (*bool, bool) {
	if o == nil || o.ShowSimquadratLogo == nil {
		return nil, false
	}
	return o.ShowSimquadratLogo, true
}

// HasShowSimquadratLogo returns a boolean if a field has been set.
func (o *PropertiesResponse) HasShowSimquadratLogo() bool {
	if o != nil && o.ShowSimquadratLogo != nil {
		return true
	}

	return false
}

// SetShowSimquadratLogo gets a reference to the given bool and assigns it to the ShowSimquadratLogo field.
func (o *PropertiesResponse) SetShowSimquadratLogo(v bool) {
	o.ShowSimquadratLogo = &v
}

// GetIdentityVerificationRequiredForMobile returns the IdentityVerificationRequiredForMobile field value if set, zero value otherwise.
func (o *PropertiesResponse) GetIdentityVerificationRequiredForMobile() bool {
	if o == nil || o.IdentityVerificationRequiredForMobile == nil {
		var ret bool
		return ret
	}
	return *o.IdentityVerificationRequiredForMobile
}

// GetIdentityVerificationRequiredForMobileOk returns a tuple with the IdentityVerificationRequiredForMobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetIdentityVerificationRequiredForMobileOk() (*bool, bool) {
	if o == nil || o.IdentityVerificationRequiredForMobile == nil {
		return nil, false
	}
	return o.IdentityVerificationRequiredForMobile, true
}

// HasIdentityVerificationRequiredForMobile returns a boolean if a field has been set.
func (o *PropertiesResponse) HasIdentityVerificationRequiredForMobile() bool {
	if o != nil && o.IdentityVerificationRequiredForMobile != nil {
		return true
	}

	return false
}

// SetIdentityVerificationRequiredForMobile gets a reference to the given bool and assigns it to the IdentityVerificationRequiredForMobile field.
func (o *PropertiesResponse) SetIdentityVerificationRequiredForMobile(v bool) {
	o.IdentityVerificationRequiredForMobile = &v
}

// GetChatbotHuman returns the ChatbotHuman field value if set, zero value otherwise.
func (o *PropertiesResponse) GetChatbotHuman() bool {
	if o == nil || o.ChatbotHuman == nil {
		var ret bool
		return ret
	}
	return *o.ChatbotHuman
}

// GetChatbotHumanOk returns a tuple with the ChatbotHuman field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetChatbotHumanOk() (*bool, bool) {
	if o == nil || o.ChatbotHuman == nil {
		return nil, false
	}
	return o.ChatbotHuman, true
}

// HasChatbotHuman returns a boolean if a field has been set.
func (o *PropertiesResponse) HasChatbotHuman() bool {
	if o != nil && o.ChatbotHuman != nil {
		return true
	}

	return false
}

// SetChatbotHuman gets a reference to the given bool and assigns it to the ChatbotHuman field.
func (o *PropertiesResponse) SetChatbotHuman(v bool) {
	o.ChatbotHuman = &v
}

// GetChatbotUsingInformalLanguage returns the ChatbotUsingInformalLanguage field value if set, zero value otherwise.
func (o *PropertiesResponse) GetChatbotUsingInformalLanguage() bool {
	if o == nil || o.ChatbotUsingInformalLanguage == nil {
		var ret bool
		return ret
	}
	return *o.ChatbotUsingInformalLanguage
}

// GetChatbotUsingInformalLanguageOk returns a tuple with the ChatbotUsingInformalLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetChatbotUsingInformalLanguageOk() (*bool, bool) {
	if o == nil || o.ChatbotUsingInformalLanguage == nil {
		return nil, false
	}
	return o.ChatbotUsingInformalLanguage, true
}

// HasChatbotUsingInformalLanguage returns a boolean if a field has been set.
func (o *PropertiesResponse) HasChatbotUsingInformalLanguage() bool {
	if o != nil && o.ChatbotUsingInformalLanguage != nil {
		return true
	}

	return false
}

// SetChatbotUsingInformalLanguage gets a reference to the given bool and assigns it to the ChatbotUsingInformalLanguage field.
func (o *PropertiesResponse) SetChatbotUsingInformalLanguage(v bool) {
	o.ChatbotUsingInformalLanguage = &v
}

// GetMultiSimProduct returns the MultiSimProduct field value if set, zero value otherwise.
func (o *PropertiesResponse) GetMultiSimProduct() bool {
	if o == nil || o.MultiSimProduct == nil {
		var ret bool
		return ret
	}
	return *o.MultiSimProduct
}

// GetMultiSimProductOk returns a tuple with the MultiSimProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetMultiSimProductOk() (*bool, bool) {
	if o == nil || o.MultiSimProduct == nil {
		return nil, false
	}
	return o.MultiSimProduct, true
}

// HasMultiSimProduct returns a boolean if a field has been set.
func (o *PropertiesResponse) HasMultiSimProduct() bool {
	if o != nil && o.MultiSimProduct != nil {
		return true
	}

	return false
}

// SetMultiSimProduct gets a reference to the given bool and assigns it to the MultiSimProduct field.
func (o *PropertiesResponse) SetMultiSimProduct(v bool) {
	o.MultiSimProduct = &v
}

// GetProductWithoutBaseFee returns the ProductWithoutBaseFee field value if set, zero value otherwise.
func (o *PropertiesResponse) GetProductWithoutBaseFee() bool {
	if o == nil || o.ProductWithoutBaseFee == nil {
		var ret bool
		return ret
	}
	return *o.ProductWithoutBaseFee
}

// GetProductWithoutBaseFeeOk returns a tuple with the ProductWithoutBaseFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetProductWithoutBaseFeeOk() (*bool, bool) {
	if o == nil || o.ProductWithoutBaseFee == nil {
		return nil, false
	}
	return o.ProductWithoutBaseFee, true
}

// HasProductWithoutBaseFee returns a boolean if a field has been set.
func (o *PropertiesResponse) HasProductWithoutBaseFee() bool {
	if o != nil && o.ProductWithoutBaseFee != nil {
		return true
	}

	return false
}

// SetProductWithoutBaseFee gets a reference to the given bool and assigns it to the ProductWithoutBaseFee field.
func (o *PropertiesResponse) SetProductWithoutBaseFee(v bool) {
	o.ProductWithoutBaseFee = &v
}

// GetVoipOnlyProduct returns the VoipOnlyProduct field value if set, zero value otherwise.
func (o *PropertiesResponse) GetVoipOnlyProduct() bool {
	if o == nil || o.VoipOnlyProduct == nil {
		var ret bool
		return ret
	}
	return *o.VoipOnlyProduct
}

// GetVoipOnlyProductOk returns a tuple with the VoipOnlyProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetVoipOnlyProductOk() (*bool, bool) {
	if o == nil || o.VoipOnlyProduct == nil {
		return nil, false
	}
	return o.VoipOnlyProduct, true
}

// HasVoipOnlyProduct returns a boolean if a field has been set.
func (o *PropertiesResponse) HasVoipOnlyProduct() bool {
	if o != nil && o.VoipOnlyProduct != nil {
		return true
	}

	return false
}

// SetVoipOnlyProduct gets a reference to the given bool and assigns it to the VoipOnlyProduct field.
func (o *PropertiesResponse) SetVoipOnlyProduct(v bool) {
	o.VoipOnlyProduct = &v
}

// GetMobileOnlyProduct returns the MobileOnlyProduct field value if set, zero value otherwise.
func (o *PropertiesResponse) GetMobileOnlyProduct() bool {
	if o == nil || o.MobileOnlyProduct == nil {
		var ret bool
		return ret
	}
	return *o.MobileOnlyProduct
}

// GetMobileOnlyProductOk returns a tuple with the MobileOnlyProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesResponse) GetMobileOnlyProductOk() (*bool, bool) {
	if o == nil || o.MobileOnlyProduct == nil {
		return nil, false
	}
	return o.MobileOnlyProduct, true
}

// HasMobileOnlyProduct returns a boolean if a field has been set.
func (o *PropertiesResponse) HasMobileOnlyProduct() bool {
	if o != nil && o.MobileOnlyProduct != nil {
		return true
	}

	return false
}

// SetMobileOnlyProduct gets a reference to the given bool and assigns it to the MobileOnlyProduct field.
func (o *PropertiesResponse) SetMobileOnlyProduct(v bool) {
	o.MobileOnlyProduct = &v
}

func (o PropertiesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdentityVerificationRequired != nil {
		toSerialize["identityVerificationRequired"] = o.IdentityVerificationRequired
	}
	if o.VerificationLetterCodeRequired != nil {
		toSerialize["verificationLetterCodeRequired"] = o.VerificationLetterCodeRequired
	}
	if o.ShowSipCredentials != nil {
		toSerialize["showSipCredentials"] = o.ShowSipCredentials
	}
	if o.ShowRegisterDndOption != nil {
		toSerialize["showRegisterDndOption"] = o.ShowRegisterDndOption
	}
	if o.ShowDisplaySingleLineOption != nil {
		toSerialize["showDisplaySingleLineOption"] = o.ShowDisplaySingleLineOption
	}
	if o.ShowClick2DialButton != nil {
		toSerialize["showClick2DialButton"] = o.ShowClick2DialButton
	}
	if o.ShowVerificationLetter != nil {
		toSerialize["showVerificationLetter"] = o.ShowVerificationLetter
	}
	if o.HasDedicatedAdminArea != nil {
		toSerialize["hasDedicatedAdminArea"] = o.HasDedicatedAdminArea
	}
	if o.ShowSimRelevantOptions != nil {
		toSerialize["showSimRelevantOptions"] = o.ShowSimRelevantOptions
	}
	if o.ShowESimOptions != nil {
		toSerialize["showESimOptions"] = o.ShowESimOptions
	}
	if o.ShowEventTimeToLiveHint != nil {
		toSerialize["showEventTimeToLiveHint"] = o.ShowEventTimeToLiveHint
	}
	if o.ShowNettoPrices != nil {
		toSerialize["showNettoPrices"] = o.ShowNettoPrices
	}
	if o.ShowBasicLogo != nil {
		toSerialize["showBasicLogo"] = o.ShowBasicLogo
	}
	if o.ShowSimquadratLogo != nil {
		toSerialize["showSimquadratLogo"] = o.ShowSimquadratLogo
	}
	if o.IdentityVerificationRequiredForMobile != nil {
		toSerialize["identityVerificationRequiredForMobile"] = o.IdentityVerificationRequiredForMobile
	}
	if o.ChatbotHuman != nil {
		toSerialize["chatbotHuman"] = o.ChatbotHuman
	}
	if o.ChatbotUsingInformalLanguage != nil {
		toSerialize["chatbotUsingInformalLanguage"] = o.ChatbotUsingInformalLanguage
	}
	if o.MultiSimProduct != nil {
		toSerialize["multiSimProduct"] = o.MultiSimProduct
	}
	if o.ProductWithoutBaseFee != nil {
		toSerialize["productWithoutBaseFee"] = o.ProductWithoutBaseFee
	}
	if o.VoipOnlyProduct != nil {
		toSerialize["voipOnlyProduct"] = o.VoipOnlyProduct
	}
	if o.MobileOnlyProduct != nil {
		toSerialize["mobileOnlyProduct"] = o.MobileOnlyProduct
	}
	return json.Marshal(toSerialize)
}

type NullablePropertiesResponse struct {
	value *PropertiesResponse
	isSet bool
}

func (v NullablePropertiesResponse) Get() *PropertiesResponse {
	return v.value
}

func (v *NullablePropertiesResponse) Set(val *PropertiesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertiesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertiesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertiesResponse(val *PropertiesResponse) *NullablePropertiesResponse {
	return &NullablePropertiesResponse{value: val, isSet: true}
}

func (v NullablePropertiesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertiesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


