/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RequestPasswordResetRequest struct for RequestPasswordResetRequest
type RequestPasswordResetRequest struct {
	Username *string `json:"username,omitempty"`
}

// NewRequestPasswordResetRequest instantiates a new RequestPasswordResetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPasswordResetRequest() *RequestPasswordResetRequest {
	this := RequestPasswordResetRequest{}
	return &this
}

// NewRequestPasswordResetRequestWithDefaults instantiates a new RequestPasswordResetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPasswordResetRequestWithDefaults() *RequestPasswordResetRequest {
	this := RequestPasswordResetRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *RequestPasswordResetRequest) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPasswordResetRequest) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *RequestPasswordResetRequest) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *RequestPasswordResetRequest) SetUsername(v string) {
	o.Username = &v
}

func (o RequestPasswordResetRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	return json.Marshal(toSerialize)
}

type NullableRequestPasswordResetRequest struct {
	value *RequestPasswordResetRequest
	isSet bool
}

func (v NullableRequestPasswordResetRequest) Get() *RequestPasswordResetRequest {
	return v.value
}

func (v *NullableRequestPasswordResetRequest) Set(val *RequestPasswordResetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPasswordResetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPasswordResetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPasswordResetRequest(val *RequestPasswordResetRequest) *NullableRequestPasswordResetRequest {
	return &NullableRequestPasswordResetRequest{value: val, isSet: true}
}

func (v NullableRequestPasswordResetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPasswordResetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


