/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmsExtensionsResponse struct for SmsExtensionsResponse
type SmsExtensionsResponse struct {
	Items []SmsExtensionResponse `json:"items,omitempty"`
}

// NewSmsExtensionsResponse instantiates a new SmsExtensionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsExtensionsResponse() *SmsExtensionsResponse {
	this := SmsExtensionsResponse{}
	return &this
}

// NewSmsExtensionsResponseWithDefaults instantiates a new SmsExtensionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsExtensionsResponseWithDefaults() *SmsExtensionsResponse {
	this := SmsExtensionsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SmsExtensionsResponse) GetItems() []SmsExtensionResponse {
	if o == nil || o.Items == nil {
		var ret []SmsExtensionResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsExtensionsResponse) GetItemsOk() ([]SmsExtensionResponse, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SmsExtensionsResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []SmsExtensionResponse and assigns it to the Items field.
func (o *SmsExtensionsResponse) SetItems(v []SmsExtensionResponse) {
	o.Items = v
}

func (o SmsExtensionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableSmsExtensionsResponse struct {
	value *SmsExtensionsResponse
	isSet bool
}

func (v NullableSmsExtensionsResponse) Get() *SmsExtensionsResponse {
	return v.value
}

func (v *NullableSmsExtensionsResponse) Set(val *SmsExtensionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsExtensionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsExtensionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsExtensionsResponse(val *SmsExtensionsResponse) *NullableSmsExtensionsResponse {
	return &NullableSmsExtensionsResponse{value: val, isSet: true}
}

func (v NullableSmsExtensionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsExtensionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


