/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ChangePasswordRequest struct for ChangePasswordRequest
type ChangePasswordRequest struct {
	Password *string `json:"password,omitempty"`
	PasswordRepeat *string `json:"passwordRepeat,omitempty"`
}

// NewChangePasswordRequest instantiates a new ChangePasswordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangePasswordRequest() *ChangePasswordRequest {
	this := ChangePasswordRequest{}
	return &this
}

// NewChangePasswordRequestWithDefaults instantiates a new ChangePasswordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangePasswordRequestWithDefaults() *ChangePasswordRequest {
	this := ChangePasswordRequest{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ChangePasswordRequest) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangePasswordRequest) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ChangePasswordRequest) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ChangePasswordRequest) SetPassword(v string) {
	o.Password = &v
}

// GetPasswordRepeat returns the PasswordRepeat field value if set, zero value otherwise.
func (o *ChangePasswordRequest) GetPasswordRepeat() string {
	if o == nil || o.PasswordRepeat == nil {
		var ret string
		return ret
	}
	return *o.PasswordRepeat
}

// GetPasswordRepeatOk returns a tuple with the PasswordRepeat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangePasswordRequest) GetPasswordRepeatOk() (*string, bool) {
	if o == nil || o.PasswordRepeat == nil {
		return nil, false
	}
	return o.PasswordRepeat, true
}

// HasPasswordRepeat returns a boolean if a field has been set.
func (o *ChangePasswordRequest) HasPasswordRepeat() bool {
	if o != nil && o.PasswordRepeat != nil {
		return true
	}

	return false
}

// SetPasswordRepeat gets a reference to the given string and assigns it to the PasswordRepeat field.
func (o *ChangePasswordRequest) SetPasswordRepeat(v string) {
	o.PasswordRepeat = &v
}

func (o ChangePasswordRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.PasswordRepeat != nil {
		toSerialize["passwordRepeat"] = o.PasswordRepeat
	}
	return json.Marshal(toSerialize)
}

type NullableChangePasswordRequest struct {
	value *ChangePasswordRequest
	isSet bool
}

func (v NullableChangePasswordRequest) Get() *ChangePasswordRequest {
	return v.value
}

func (v *NullableChangePasswordRequest) Set(val *ChangePasswordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangePasswordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangePasswordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangePasswordRequest(val *ChangePasswordRequest) *NullableChangePasswordRequest {
	return &NullableChangePasswordRequest{value: val, isSet: true}
}

func (v NullableChangePasswordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangePasswordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


