/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResendFaxRequest struct for ResendFaxRequest
type ResendFaxRequest struct {
	FaxId string `json:"faxId"`
	FaxlineId *string `json:"faxlineId,omitempty"`
}

// NewResendFaxRequest instantiates a new ResendFaxRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResendFaxRequest(faxId string) *ResendFaxRequest {
	this := ResendFaxRequest{}
	this.FaxId = faxId
	return &this
}

// NewResendFaxRequestWithDefaults instantiates a new ResendFaxRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResendFaxRequestWithDefaults() *ResendFaxRequest {
	this := ResendFaxRequest{}
	return &this
}

// GetFaxId returns the FaxId field value
func (o *ResendFaxRequest) GetFaxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FaxId
}

// GetFaxIdOk returns a tuple with the FaxId field value
// and a boolean to check if the value has been set.
func (o *ResendFaxRequest) GetFaxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FaxId, true
}

// SetFaxId sets field value
func (o *ResendFaxRequest) SetFaxId(v string) {
	o.FaxId = v
}

// GetFaxlineId returns the FaxlineId field value if set, zero value otherwise.
func (o *ResendFaxRequest) GetFaxlineId() string {
	if o == nil || o.FaxlineId == nil {
		var ret string
		return ret
	}
	return *o.FaxlineId
}

// GetFaxlineIdOk returns a tuple with the FaxlineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResendFaxRequest) GetFaxlineIdOk() (*string, bool) {
	if o == nil || o.FaxlineId == nil {
		return nil, false
	}
	return o.FaxlineId, true
}

// HasFaxlineId returns a boolean if a field has been set.
func (o *ResendFaxRequest) HasFaxlineId() bool {
	if o != nil && o.FaxlineId != nil {
		return true
	}

	return false
}

// SetFaxlineId gets a reference to the given string and assigns it to the FaxlineId field.
func (o *ResendFaxRequest) SetFaxlineId(v string) {
	o.FaxlineId = &v
}

func (o ResendFaxRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["faxId"] = o.FaxId
	}
	if o.FaxlineId != nil {
		toSerialize["faxlineId"] = o.FaxlineId
	}
	return json.Marshal(toSerialize)
}

type NullableResendFaxRequest struct {
	value *ResendFaxRequest
	isSet bool
}

func (v NullableResendFaxRequest) Get() *ResendFaxRequest {
	return v.value
}

func (v *NullableResendFaxRequest) Set(val *ResendFaxRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResendFaxRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResendFaxRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResendFaxRequest(val *ResendFaxRequest) *NullableResendFaxRequest {
	return &NullableResendFaxRequest{value: val, isSet: true}
}

func (v NullableResendFaxRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResendFaxRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


