/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddCallEmailNotificationRequest struct for AddCallEmailNotificationRequest
type AddCallEmailNotificationRequest struct {
	EndpointId string `json:"endpointId"`
	Direction string `json:"direction"`
	Cause string `json:"cause"`
	Email string `json:"email"`
}

// NewAddCallEmailNotificationRequest instantiates a new AddCallEmailNotificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddCallEmailNotificationRequest(endpointId string, direction string, cause string, email string) *AddCallEmailNotificationRequest {
	this := AddCallEmailNotificationRequest{}
	this.EndpointId = endpointId
	this.Direction = direction
	this.Cause = cause
	this.Email = email
	return &this
}

// NewAddCallEmailNotificationRequestWithDefaults instantiates a new AddCallEmailNotificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddCallEmailNotificationRequestWithDefaults() *AddCallEmailNotificationRequest {
	this := AddCallEmailNotificationRequest{}
	return &this
}

// GetEndpointId returns the EndpointId field value
func (o *AddCallEmailNotificationRequest) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *AddCallEmailNotificationRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *AddCallEmailNotificationRequest) SetEndpointId(v string) {
	o.EndpointId = v
}

// GetDirection returns the Direction field value
func (o *AddCallEmailNotificationRequest) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *AddCallEmailNotificationRequest) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *AddCallEmailNotificationRequest) SetDirection(v string) {
	o.Direction = v
}

// GetCause returns the Cause field value
func (o *AddCallEmailNotificationRequest) GetCause() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cause
}

// GetCauseOk returns a tuple with the Cause field value
// and a boolean to check if the value has been set.
func (o *AddCallEmailNotificationRequest) GetCauseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cause, true
}

// SetCause sets field value
func (o *AddCallEmailNotificationRequest) SetCause(v string) {
	o.Cause = v
}

// GetEmail returns the Email field value
func (o *AddCallEmailNotificationRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AddCallEmailNotificationRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AddCallEmailNotificationRequest) SetEmail(v string) {
	o.Email = v
}

func (o AddCallEmailNotificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["endpointId"] = o.EndpointId
	}
	if true {
		toSerialize["direction"] = o.Direction
	}
	if true {
		toSerialize["cause"] = o.Cause
	}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableAddCallEmailNotificationRequest struct {
	value *AddCallEmailNotificationRequest
	isSet bool
}

func (v NullableAddCallEmailNotificationRequest) Get() *AddCallEmailNotificationRequest {
	return v.value
}

func (v *NullableAddCallEmailNotificationRequest) Set(val *AddCallEmailNotificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddCallEmailNotificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddCallEmailNotificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddCallEmailNotificationRequest(val *AddCallEmailNotificationRequest) *NullableAddCallEmailNotificationRequest {
	return &NullableAddCallEmailNotificationRequest{value: val, isSet: true}
}

func (v NullableAddCallEmailNotificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddCallEmailNotificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


