/*
sipgate API

This is the sipgate REST API documentation. We build our applications on this API and we invite you to use it too.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VoicemailsResponse struct for VoicemailsResponse
type VoicemailsResponse struct {
	Items []SimpleVoicemailResponse `json:"items,omitempty"`
}

// NewVoicemailsResponse instantiates a new VoicemailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoicemailsResponse() *VoicemailsResponse {
	this := VoicemailsResponse{}
	return &this
}

// NewVoicemailsResponseWithDefaults instantiates a new VoicemailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoicemailsResponseWithDefaults() *VoicemailsResponse {
	this := VoicemailsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *VoicemailsResponse) GetItems() []SimpleVoicemailResponse {
	if o == nil || o.Items == nil {
		var ret []SimpleVoicemailResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoicemailsResponse) GetItemsOk() ([]SimpleVoicemailResponse, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *VoicemailsResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []SimpleVoicemailResponse and assigns it to the Items field.
func (o *VoicemailsResponse) SetItems(v []SimpleVoicemailResponse) {
	o.Items = v
}

func (o VoicemailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableVoicemailsResponse struct {
	value *VoicemailsResponse
	isSet bool
}

func (v NullableVoicemailsResponse) Get() *VoicemailsResponse {
	return v.value
}

func (v *NullableVoicemailsResponse) Set(val *VoicemailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVoicemailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVoicemailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoicemailsResponse(val *VoicemailsResponse) *NullableVoicemailsResponse {
	return &NullableVoicemailsResponse{value: val, isSet: true}
}

func (v NullableVoicemailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoicemailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


